### ISSUE TITLE
Implement Basic Completion Support (Task Set1) for Language Server

### ISSUE THREAD

**Issue by nadeeshaan** [ballerinalang/language-server#14]
**Description:**
As the initial cut, we need to provide the basic language completion support

**Tasks List:**
- [x] Port Composer's completion Engine
- [x] Verify suggestion and auto-completion
- [x] Integrate with new workspace implementation

**Comment by nadeeshaan** [comment]
Closing the issue, since the tasks have been addressed with the following
https://github.com/ballerinalang/language-server/pull/15
https://github.com/ballerinalang/language-server/pull/20
