### ISSUE TITLE
Implementing language server support for Composer

### ISSUE THREAD

**Issue by NipunaMarcus** [ballerinalang/language-server#16]
**Description:**
this is to track the progress of implementing the language server support for composer.

**Task List:**
- [x] Add dependencies to get the language server
- [x] Refactor old language server implementation to use the new language server implementation
- [x] Edit the client side code to fetch and send necessary data.

**Related Issues:**
https://github.com/ballerinalang/composer/issues/4740
